//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhukkhad.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingMaster
    {
        public int BookId { get; set; }
        public string Name { get; set; }
        public string EAddress { get; set; }
        public string EDate { get; set; }
        public string ECallTime { get; set; }
        public string CName { get; set; }
        public string CPhone { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
    }
}
